import streamlit as st
 
st.title("Welcome to Rubies Technologies")
st.image("https://tse4.mm.bing.net/th/id/OIP.xq1M5e621HnccPMQ6I1GOgHaHa?pid=ImgDet&rs=1")
st.subheader("We are Building the African Future")
st.write("Rubies Technologies is a social enterprise that is focused on building the future, we believe in the possibilities of kids and teenagers improving lives and solving problems with the use of technology. We are dedicated to inspiring and teaching kids to be innovative and to solve problems.")
st.write("As we all know, the technology industry is fast growing at an incredible pace and the need for designers, programmers, problem solvers, and innovators keep increasing. It is therefore imperative that concentrated effort be directed towards teaching the younger generation in order to fill the tech jobs/gaps that are believed to be coming in the next decades.")
st.write("As an institute that is known for sustainable development and innovation by training children, we strongly believe in educating the younger generation, this is because children are the leaders of tomorrow.")
st.subheader("Mission")
st.write("To equip, train, and empower Africans to learn new technological and digital skills that can be used around the world.")
st.subheader("Vission")
st.write("To ensure all Africans are digitally and technologically empowered to solve problems and create value.")
st.header("What we do at Rubies Tech - Adeola Lawal")
st.video("https://youtu.be/BPXOqOSUU2E")
st.header("Why your kids should code - Theresa")
st.video("https://youtu.be/io_k46qK2ew")
st.header("Rubies Code School")
st.video("https://youtu.be/6HN3nmmP480")
st.header("Rubies Technologies visits Abule Ijoko")
st.video("https://youtu.be/XcXUV4Akc0g")
st.header("2022 is great, can wait for 2023")
st.video("https://youtu.be/Gf5Bf-Y8Jc4")